/* File used by Spring Boot to load the h2 database tables */
INSERT INTO LOOKUP_MARITAL_STATUS (MAR_STATUS_CD, MAR_STATUS_TX) values ('A','Marriage Annuled');
INSERT INTO LOOKUP_MARITAL_STATUS (MAR_STATUS_CD, MAR_STATUS_TX) values ('D','Divorced');
INSERT INTO LOOKUP_MARITAL_STATUS (MAR_STATUS_CD, MAR_STATUS_TX) values ('I','Interlocutory Decree');
INSERT INTO LOOKUP_MARITAL_STATUS (MAR_STATUS_CD, MAR_STATUS_TX) values ('L','Legally Separated');
INSERT INTO LOOKUP_MARITAL_STATUS (MAR_STATUS_CD, MAR_STATUS_TX) values ('M','Married');
INSERT INTO LOOKUP_MARITAL_STATUS (MAR_STATUS_CD, MAR_STATUS_TX) values ('N','Never Married');
INSERT INTO LOOKUP_MARITAL_STATUS (MAR_STATUS_CD, MAR_STATUS_TX) values ('R','Separated (Other Than Legally)');
INSERT INTO LOOKUP_MARITAL_STATUS (MAR_STATUS_CD, MAR_STATUS_TX) values ('W','Widowed');

INSERT INTO LOOKUP_RATING_LEVEL (RATING_CD, RATING_TX) values (1,'Does Not Meet Expectations');
INSERT INTO LOOKUP_RATING_LEVEL (RATING_CD, RATING_TX) values (2,'Meets Expectations');
INSERT INTO LOOKUP_RATING_LEVEL (RATING_CD, RATING_TX) values (3,'Exceeds Expectations');
INSERT INTO LOOKUP_RATING_LEVEL (RATING_CD, RATING_TX) values (4,'Superb');



INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (1,'Question One','Meets guidelines for Question One',100,{d '1970-01-01'},{d '9999-12-31'});
INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (2,'Question Two','Meets guidelines for Question Two',200,{d '1970-01-01'},{d '9999-12-31'});
INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (3,'Question Three','Meets guidelines for Question Three',300,{d '1970-01-01'},{d '9999-12-31'});
INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (4,'Question Four','Meets guidelines for Question Four',400,{d '1970-01-01'},{d '9999-12-31'});
INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (5,'Question Five','Meets guidelines for Question Five',500,{d '1970-01-01'},{d '9999-12-31'});
INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (6,'Question Six','Meets guidelines for Question Six',600,{d '1970-01-01'},{d '9999-12-31'});
INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (7,'Question Seven','Meets guidelines for Question Seven',700,{d '1970-01-01'},{d '9999-12-31'});
INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (8,'Question Eight','Meets guidelines for Question Eight',800,{d '1970-01-01'},{d '9999-12-31'});
INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (9,'Question Nine','Meets guidelines for Question Nine',900,{d '1970-01-01'},{d '9999-12-31'});
INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (10,'Question Ten','Meets guidelines for Question Ten',1000,{d '1970-01-01'},{d '9999-12-31'});
INSERT INTO PERSON_EVAL_QUESTION (PERS_EVAL_QUESTION_ID,QUESTION_NAME,QUESTION_TX,QUESTION_ORDER,QUESTION_BEG_DT,QUESTION_END_DT) VALUES (11,'Question Eleven','Meets guidelines for Question Eleven',1100,{d '1970-01-01'},{d '9999-12-31'});
