/**
 * Contains classes that use the style of REST function definition, where a Repository interface is defined for an
 * Entity with some functionality whose code is auto-generated by Spring, and that functionality is
 * extended through the use of an interface that declares the custom methods and a Repository Impl
 * that implements the custom methods.
 *  
 * @author Jerry Hehman
 *
 */
package com.jerryhehman.howto.springjparest.repository.customimpl;