package com.jerryhehman.howto.springjparest.domain;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;

/**
 * SchEvalAnswer generated by hbm2java
 */

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name="PERS_EVAL_ANSWER"
)
@SuppressWarnings("serial")
public class PersEvalAnswer implements java.io.Serializable {


    private PersEvalAnswerId id;
    private Short answer;
    private String createBy;
    private Date createDt;
    private String modBy;
    private Date modDt;

   public PersEvalAnswer() {
   }

	
   public PersEvalAnswer(PersEvalAnswerId id, String createBy, Date createDt) {
       this.id = id;
       this.createBy = createBy;
       this.createDt = createDt;
   }
   public PersEvalAnswer(PersEvalAnswerId id, Short answer, String createBy, Date createDt, String modBy, Date modDt) {
      this.id = id;
      this.answer = answer;
      this.createBy = createBy;
      this.createDt = createDt;
      this.modBy = modBy;
      this.modDt = modDt;
   }
  
    @EmbeddedId

   
   @AttributeOverrides( {
       @AttributeOverride(name="personId", column=@Column(name="PERSON_ID", nullable=false, length=12) ), 
       @AttributeOverride(name="personEvalId", column=@Column(name="PERSON_EVAL_ID", nullable=false) ), 
       @AttributeOverride(name="persEvalQuestionId", column=@Column(name="PERS_EVAL_QUESTION_ID", nullable=false) ) } )
   public PersEvalAnswerId getId() {
       return this.id;
   }
   
   public void setId(PersEvalAnswerId id) {
       this.id = id;
   }

   
   @Column(name="ANSWER")
   public Short getAnswer() {
       return this.answer;
   }
   
   public void setAnswer(Short answer) {
       this.answer = answer;
   }

   
   @Column(name="CREATE_BY", nullable=false, length=30)
   public String getCreateBy() {
       return this.createBy;
   }
   
   public void setCreateBy(String createBy) {
       this.createBy = createBy;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name="CREATE_DT", nullable=false, length=23)
   public Date getCreateDt() {
       return this.createDt;
   }
   
   public void setCreateDt(Date createDt) {
       this.createDt = createDt;
   }

   
   @Column(name="MOD_BY", length=30)
   public String getModBy() {
       return this.modBy;
   }
   
   public void setModBy(String modBy) {
       this.modBy = modBy;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name="MOD_DT", length=23)
   public Date getModDt() {
       return this.modDt;
   }
   
   public void setModDt(Date modDt) {
       this.modDt = modDt;
   }

   /**
    * toString
    * @return String
    */
    @Override
    public String toString() {
	  StringBuilder buffer = new StringBuilder();

     buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
     buffer.append("id").append("='").append(getId()).append("' ");			
     buffer.append("answer").append("='").append(getAnswer()).append("' ");			
     buffer.append("createBy").append("='").append(getCreateBy()).append("' ");			
     buffer.append("createDt").append("='").append(getCreateDt()).append("' ");			
     buffer.append("modBy").append("='").append(getModBy()).append("' ");			
     buffer.append("modDt").append("='").append(getModDt()).append("' ");			
     buffer.append("]");
     
     return buffer.toString();
    }

   @Override
   public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersEvalAnswer) ) return false;
		 PersEvalAnswer castOther = ( PersEvalAnswer ) other; 
        
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
&& ( (this.getAnswer()==castOther.getAnswer()) || ( this.getAnswer()!=null && castOther.getAnswer()!=null && this.getAnswer().equals(castOther.getAnswer()) ) )
&& ( (this.getCreateBy()==castOther.getCreateBy()) || ( this.getCreateBy()!=null && castOther.getCreateBy()!=null && this.getCreateBy().equals(castOther.getCreateBy()) ) )
&& ( (this.getCreateDt()==castOther.getCreateDt()) || ( this.getCreateDt()!=null && castOther.getCreateDt()!=null && this.getCreateDt().equals(castOther.getCreateDt()) ) )
&& ( (this.getModBy()==castOther.getModBy()) || ( this.getModBy()!=null && castOther.getModBy()!=null && this.getModBy().equals(castOther.getModBy()) ) )
&& ( (this.getModDt()==castOther.getModDt()) || ( this.getModDt()!=null && castOther.getModDt()!=null && this.getModDt().equals(castOther.getModDt()) ) );
  }
  
   @Override
  public int hashCode() {
        int result = 17;
        
        result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
        result = 37 * result + ( getAnswer() == null ? 0 : this.getAnswer().hashCode() );
        result = 37 * result + ( getCreateBy() == null ? 0 : this.getCreateBy().hashCode() );
        result = 37 * result + ( getCreateDt() == null ? 0 : this.getCreateDt().hashCode() );
        result = 37 * result + ( getModBy() == null ? 0 : this.getModBy().hashCode() );
        result = 37 * result + ( getModDt() == null ? 0 : this.getModDt().hashCode() );
        return result;
  }   


}

